name: Bug Bounties
description: Report security vulnerabilities or bugs for financial rewards.
title: "[Bug Bounty] Title of Vulnerability"
labels: []
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: Enter the title of the vulnerability
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief summary of the vulnerability.
      placeholder: Provide a summary
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability.
      placeholder: Provide the steps to reproduce the issue
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain the potential impact of the vulnerability.
      placeholder: Describe the impact
    validations:
      required: true

  - type: textarea
    id: supporting_material
    attributes:
      label: Supporting Material
      description: Include code snippets, screenshots, or logs.
      placeholder: Provide any supporting material
    validations:
      required: false

  - type: input
    id: reward
    attributes:
      label: Estimate Suggested Reward
      description: In $.
      placeholder: Suggested reward amount
    validations:
      required: false
