name: Community Resources
description: Suggest improvements or additions to community resources.
title: "[Resource Improvement] Title of Resource"
labels: []
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: Enter the title of the resource improvement
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief summary of the resource improvement.
      placeholder: Provide a summary
    validations:
      required: true

  - type: textarea
    id: changes_made
    attributes:
      label: Changes Made
      description: Describe the specific changes or additions made to the resource.
      placeholder: Detail the changes made
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain how the changes improve the resource for the community.
      placeholder: Describe the impact of the changes
    validations:
      required: true

  - type: textarea
    id: supporting_material
    attributes:
      label: Supporting Material
      description: Include screenshots or snippets if applicable.
      placeholder: Provide any supporting material
    validations:
      required: false

  - type: input
    id: reward
    attributes:
      label: Estimate Suggested Reward
      description: In $.
      placeholder: Suggested reward amount
    validations:
      required: false
