name: Educational Materials
description: Create and submit educational content for new developers.
title: "[Educational Material] Title of Content"
labels: []
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: Enter the title of your educational content
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Provide an overview of the educational content and its goals.
      placeholder: Provide an overview
    validations:
      required: true

  - type: textarea
    id: topics_covered
    attributes:
      label: Topics Covered
      description: List the topics covered in the material.
      placeholder: List the topics covered
    validations:
      required: true

  - type: textarea
    id: intended_audience
    attributes:
      label: Intended Audience
      description: Specify the target audience (e.g., beginner developers).
      placeholder: Specify the intended audience
    validations:
      required: true

  - type: textarea
    id: supporting_material
    attributes:
      label: Supporting Material
      description: Include links to content, code examples, visuals, or additional resources.
      placeholder: Provide any supporting material
    validations:
      required: false

  - type: input
    id: reward
    attributes:
      label: Estimate Suggested Reward
      description: In $.
      placeholder: Suggested reward amount
    validations:
      required: false
